---
- name: Install MariaDB on Debian
  hosts: debian
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MariaDB server
      apt:
        name:
          - mariadb-server
          - mariadb-client
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

